apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169260483
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169260483
    app.kubernetes.io/part-of: test-app-169260483
  name: go-169260483
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-169260483
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-169260483
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/redhat-user-workloads/skhileri-tenant/test-app-169260483/go-169260483@sha256:08bb1a9c00f84af08aa90cde810aafe141cb8bf1759e53e6fb1f2057915b3ca3
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
