apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169260483
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169260483
    app.kubernetes.io/part-of: test-app-169260483
  name: go-169260483
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-169260483
status:
  loadBalancer: {}
