apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-169260483
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/skhileri-tenant/test-app-169260483/go-169260483@sha256:08bb1a9c00f84af08aa90cde810aafe141cb8bf1759e53e6fb1f2057915b3ca3
        name: my-go
        resources: {}
status: {}
