apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-169260483
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/skhileri-tenant/test-app-169260483/go-169260483@sha256:33f4b935c724416338eadc11f11766c6769ba59c1308e870b0ff134faa2be578
        name: my-go
        resources: {}
status: {}
